[package]
name = "oxide-serverd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "oxide-serverd"
path = "src/main.rs"

[dependencies]
oxide-common = { path = "../common" }
oxide-wg-core = { path = "../wg-core" }
oxide-net-linux = { path = "../net-linux" }
oxide-control-client = { path = "../control-client" }
oxide-relay = { path = "../relay" }
oxide-pq = { path = "../pq" }
base64 = "0.22"
tokio = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
ipnet = { workspace = true }

[dev-dependencies]
oxide-control-plane = { path = "../control-plane" }
oxide-wg-core = { path = "../wg-core", features = ["test-util"] }
