//! Oxide VPN server daemon (Milestone 1).
//!
//! Terminates WireGuard tunnels from clients and, when configured, NATs their traffic
//! to the internet (full-tunnel egress). Static config only — no control plane, DB, or
//! auth yet (that is M2).
//!
//! Requires `CAP_NET_ADMIN` (run as root in M1): it creates a TUN device, edits
//! routes/sysctls, and installs an nftables masquerade table.

use std::collections::HashSet;
use std::path::PathBuf;
use std::time::Duration;

use anyhow::{Context, Result};
use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine as _;
use clap::{Parser, Subcommand};
use ipnet::IpNet;
use oxide_relay::Relay;
use tracing::{info, warn};

use oxide_common::api::PeerEntry;
use oxide_common::{keys, Config, ControlPlaneConfig, InterfaceConfig, SecretKey, TransportKind};
use oxide_control_client::ControlClient;
use oxide_net_linux::{bring_up_interface, nat, netlink, shutdown_signal, sysctl, Netlink};
use oxide_wg_core::{Daita, Engine, EngineHandle, MimicTransport, PeerParams, Transport, TunQueue};

const IFNAME: &str = "oxide0";

#[derive(Parser)]
#[command(name = "oxide-serverd", about = "Oxide VPN server daemon")]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
// `provision` carries many one-shot flags; boxing a CLI command variant buys nothing.
#[allow(clippy::large_enum_variant)]
enum Cmd {
    /// Bring the tunnel up and serve clients.
    Up {
        #[arg(short, long, default_value = "server.toml")]
        config: PathBuf,
    },
    /// Print a fresh private key (base64), like `wg genkey`.
    Genkey,
    /// Read a private key (base64) on stdin, print its public key, like `wg pubkey`.
    Pubkey,
    /// Generate a post-quantum (ML-KEM) keypair: prints the private seed and public key.
    /// Put the seed in the server config (`pq_private_seed`) and register the public key
    /// with the control plane (`add-server --pq-public-key`).
    PqGenkey,
    /// Generate an Ed25519 **release key** for signed build manifests. Keep the seed
    /// offline; pin the public key in clients.
    AttestGenkey,
    /// Print a release-key-signed build manifest for THIS binary (version, git commit,
    /// build time, and the binary's SHA-256). Publish it so clients can verify the build.
    Manifest {
        /// Release signing seed (base64), from `attest-genkey`.
        #[arg(long)]
        key: String,
    },
    /// One-command provisioning: generate keys, register this server with the control plane
    /// (admin API), and write a ready-to-run config. Then `sudo oxide-serverd up`.
    Provision {
        /// Control-plane base URL, e.g. `http://cp.example:8080`.
        #[arg(long)]
        control_plane: String,
        /// Admin token for the control plane's admin API (or `OXIDE_ADMIN_TOKEN`).
        #[arg(long, env = "OXIDE_ADMIN_TOKEN")]
        admin_token: String,
        /// Server id to register (e.g. `us-nyc-1`).
        #[arg(long)]
        id: String,
        /// This server's public UDP endpoint clients dial, `host:port`.
        #[arg(long)]
        endpoint: String,
        /// Tunnel subnet.
        #[arg(long, default_value = "10.8.0.0/24")]
        cidr: String,
        /// UDP port to listen on.
        #[arg(long, default_value_t = 51820)]
        listen_port: u16,
        #[arg(long)]
        country: Option<String>,
        #[arg(long)]
        city: Option<String>,
        /// Soft capacity for load-based selection (0 = unlimited).
        #[arg(long, default_value_t = 0)]
        capacity: u32,
        /// Egress interface for full-tunnel NAT (adds a `[nat]` section). Omit for
        /// tunnel-only. Use `auto` to let the daemon auto-detect the default route.
        #[arg(long)]
        nat_egress: Option<String>,
        /// Wire transport: plain | obfs | quic | mimic. Non-plain generates an obfs key.
        #[arg(long, default_value = "plain")]
        transport: String,
        /// Enable DAITA (implies a stealth transport).
        #[arg(long)]
        daita: bool,
        /// Enable the post-quantum handshake (generate an ML-KEM key).
        #[arg(long)]
        pq: bool,
        /// Where to write the generated config.
        #[arg(long, default_value = "server.toml")]
        out: PathBuf,
    },
}

/// Parameters for rendering a server config (kept pure/testable).
struct ServerConfigParams<'a> {
    private_key_b64: &'a str,
    address: &'a str,
    listen_port: u16,
    dns: Option<&'a str>,
    obfuscation_key: Option<&'a str>,
    pq_private_seed: Option<&'a str>,
    transport: Option<&'a str>,
    daita: bool,
    nat_egress: Option<&'a str>,
    cp_url: &'a str,
    server_id: &'a str,
    token: &'a str,
}

/// Render a complete, valid `server.toml` from provisioning parameters.
fn render_server_config(p: &ServerConfigParams) -> String {
    let mut s = String::new();
    s.push_str("# Generated by `oxide-serverd provision`.\n[interface]\n");
    s.push_str(&format!("private_key = \"{}\"\n", p.private_key_b64));
    s.push_str(&format!("address = \"{}\"\n", p.address));
    s.push_str(&format!("listen_port = {}\n", p.listen_port));
    if let Some(dns) = p.dns {
        s.push_str(&format!("dns = \"{dns}\"\n"));
    }
    if let Some(k) = p.obfuscation_key {
        s.push_str(&format!("obfuscation_key = \"{k}\"\n"));
    }
    if let Some(t) = p.transport {
        s.push_str(&format!("transport = \"{t}\"\n"));
    }
    if p.daita {
        s.push_str("daita = true\n");
    }
    if let Some(seed) = p.pq_private_seed {
        s.push_str(&format!("pq_private_seed = \"{seed}\"\n"));
    }
    if let Some(egress) = p.nat_egress {
        s.push_str("\n[nat]\n");
        if egress != "auto" {
            s.push_str(&format!("egress = \"{egress}\"\n"));
        }
    }
    s.push_str("\n[control_plane]\n");
    s.push_str(&format!("url = \"{}\"\n", p.cp_url));
    s.push_str(&format!("server_id = \"{}\"\n", p.server_id));
    s.push_str(&format!("token = \"{}\"\n", p.token));
    s
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .init();

    match Cli::parse().cmd {
        Cmd::Genkey => {
            println!("{}", keys::generate_secret().to_base64());
            Ok(())
        }
        Cmd::Pubkey => {
            let mut line = String::new();
            std::io::stdin().read_line(&mut line)?;
            let sk: SecretKey = line
                .trim()
                .parse()
                .context("invalid private key on stdin")?;
            println!("{}", keys::public_from_secret(&sk).to_base64());
            Ok(())
        }
        Cmd::PqGenkey => {
            let (seed, public_key) = oxide_pq::generate();
            println!("pq_private_seed (server config): {}", B64.encode(&seed));
            println!(
                "pq_public_key  (add-server):     {}",
                B64.encode(&public_key)
            );
            Ok(())
        }
        Cmd::AttestGenkey => {
            let (seed, public_key) = oxide_attest::generate_release_key();
            println!("attest_signing_seed (keep offline): {}", B64.encode(seed));
            println!(
                "attest_public_key   (pin in clients): {}",
                B64.encode(public_key)
            );
            Ok(())
        }
        Cmd::Manifest { key } => {
            let seed: [u8; oxide_attest::KEY_LEN] = B64
                .decode(key.trim())
                .ok()
                .and_then(|b| b.try_into().ok())
                .context("--key must be a base64 32-byte signing seed")?;
            let manifest = oxide_attest::BuildManifest {
                version: env!("CARGO_PKG_VERSION").to_string(),
                git_commit: env!("OXIDE_GIT_COMMIT").to_string(),
                build_time: env!("OXIDE_BUILD_TIME").to_string(),
                binary_sha256: oxide_attest::self_binary_sha256().context("hashing this binary")?,
            };
            println!("{}", oxide_attest::sign_manifest(manifest, &seed).to_json());
            Ok(())
        }
        Cmd::Provision {
            control_plane,
            admin_token,
            id,
            endpoint,
            cidr,
            listen_port,
            country,
            city,
            capacity,
            nat_egress,
            transport,
            daita,
            pq,
            out,
        } => {
            provision(ProvisionArgs {
                control_plane,
                admin_token,
                id,
                endpoint,
                cidr,
                listen_port,
                country,
                city,
                capacity,
                nat_egress,
                transport,
                daita,
                pq,
                out,
            })
            .await
        }
        Cmd::Up { config } => run(config).await,
    }
}

struct ProvisionArgs {
    control_plane: String,
    admin_token: String,
    id: String,
    endpoint: String,
    cidr: String,
    listen_port: u16,
    country: Option<String>,
    city: Option<String>,
    capacity: u32,
    nat_egress: Option<String>,
    transport: String,
    daita: bool,
    pq: bool,
    out: PathBuf,
}

async fn provision(a: ProvisionArgs) -> Result<()> {
    let cidr: IpNet = a.cidr.parse().context("invalid --cidr")?;
    let server_ip = cidr.hosts().next().context("cidr has no usable hosts")?;
    let address = format!("{server_ip}/{}", cidr.prefix_len());
    let dns = server_ip.to_string();

    // Keys.
    let private_key = keys::generate_secret();
    let public_key = keys::public_from_secret(&private_key).to_base64();
    let (pq_seed, pq_public) = if a.pq {
        let (seed, pk) = oxide_pq::generate();
        (Some(B64.encode(seed)), Some(B64.encode(pk)))
    } else {
        (None, None)
    };

    // A stealth transport (or DAITA) needs an obfuscation key; generate one and settle the
    // effective transport (DAITA over "plain" is upgraded to "obfs").
    let stealth = a.transport != "plain" || a.daita;
    let obfuscation_key = stealth.then(|| keys::generate_secret().to_base64());
    let effective_transport = if a.transport == "plain" && a.daita {
        "obfs".to_string()
    } else {
        a.transport.clone()
    };
    let transport_field = (effective_transport != "plain").then_some(effective_transport.as_str());

    // Register with the control plane (admin API).
    let cc = ControlClient::new(&a.control_plane);
    let req = oxide_common::api::AdminAddServerRequest {
        id: a.id.clone(),
        public_key,
        endpoint: a.endpoint.clone(),
        cidr: cidr.to_string(),
        country: a.country.clone(),
        city: a.city.clone(),
        capacity: a.capacity,
        dns: Some(dns.clone()),
        obfuscation_key: obfuscation_key.clone(),
        pq_public_key: pq_public,
        transport: transport_field.map(str::to_string),
        daita: a.daita,
    };
    let token = cc
        .admin_add_server(&a.admin_token, &req)
        .await
        .context("registering server with the control plane")?;

    // Write the config.
    let toml = render_server_config(&ServerConfigParams {
        private_key_b64: &private_key.to_base64(),
        address: &address,
        listen_port: a.listen_port,
        dns: Some(&dns),
        obfuscation_key: obfuscation_key.as_deref(),
        pq_private_seed: pq_seed.as_deref(),
        transport: transport_field,
        daita: a.daita,
        nat_egress: a.nat_egress.as_deref(),
        cp_url: &a.control_plane,
        server_id: &a.id,
        token: &token,
    });
    std::fs::write(&a.out, toml).with_context(|| format!("writing {}", a.out.display()))?;

    println!("Provisioned server '{}' → {}", a.id, a.out.display());
    println!("  tunnel IP: {address}   endpoint: {}", a.endpoint);
    if stealth {
        println!(
            "  stealth: on (transport = {effective_transport}{})",
            if a.daita { " + daita" } else { "" }
        );
    }
    if a.pq {
        println!("  post-quantum: on");
    }
    println!(
        "Start it (needs root):  sudo oxide-serverd up --config {}",
        a.out.display()
    );
    Ok(())
}

async fn run(config_path: PathBuf) -> Result<()> {
    let cfg =
        Config::load(&config_path).with_context(|| format!("loading {}", config_path.display()))?;
    let listen_port = cfg
        .interface
        .listen_port
        .context("server config must set interface.listen_port")?;

    // Interface: TUN + address + MTU + up (over netlink).
    let nl = Netlink::connect().context("opening netlink")?;
    let (tun, _idx) = bring_up_interface(&nl, IFNAME, &cfg.interface)
        .await
        .context("bringing up tun interface")?;
    info!(iface = IFNAME, addr = %cfg.interface.address, mtu = cfg.interface.mtu(), "interface up");

    // Full-tunnel egress: forwarding + relaxed rp_filter + masquerade.
    let mut nat_egress: Option<String> = None;
    if let Some(natcfg) = &cfg.nat {
        let egress = match &natcfg.egress {
            Some(e) => e.clone(),
            None => netlink::default_route()?
                .map(|(_, dev)| dev)
                .context("could not auto-detect egress interface; set [nat] egress")?,
        };
        sysctl::enable_ip_forward().context("enabling ip_forward")?;
        sysctl::relax_rp_filter(&egress).context("relaxing rp_filter")?;
        nat::enable_masquerade(IFNAME, &egress).context("installing nftables masquerade")?;
        info!(egress = %egress, "NAT masquerade enabled (full-tunnel egress)");
        nat_egress = Some(egress);
    }

    // Build the selected wire transport (plain / obfs / quic[+decoy] / mimic).
    let transport = build_server_transport(&cfg.interface, listen_port).await?;
    info!(port = listen_port, peers = cfg.peers.len(), "listening");

    // Server-side handshake rate limit (DoS defense): cookie challenges engage above
    // this many handshake messages/second across all peers.
    const HANDSHAKE_LIMIT: u64 = 100;
    let peers = cfg.peers.iter().map(PeerParams::from_config).collect();
    let engine = Engine::build_server(
        &cfg.interface.private_key,
        peers,
        transport,
        tun,
        HANDSHAKE_LIMIT,
    );
    // DAITA (traffic-analysis defense): the server frames replies as cells and drops
    // inbound cover; the client drives the constant rate. Requires a stealth transport.
    let engine = if cfg.interface.daita {
        info!("DAITA enabled (server framing mode)");
        engine.with_daita(Daita::server())
    } else {
        engine
    };

    // Decode the post-quantum private seed (if any) so we can decapsulate each device's
    // ciphertext into its PSK during reconcile.
    let pq_seed: Option<Vec<u8>> = cfg
        .interface
        .pq_private_seed
        .as_ref()
        .and_then(|s| B64.decode(s).ok());
    if pq_seed.is_some() {
        info!("post-quantum enabled (server will derive per-peer PSKs)");
    }

    // If configured, pull the peer list from the control plane and keep it in sync.
    // The engine's peer table is runtime-mutable, so this reconciles live and the
    // data plane keeps peer state in RAM only (no on-disk peer store).
    if let Some(cp) = cfg.control_plane {
        let handle = engine.handle();
        tokio::spawn(poll_control_plane(handle, cp, pq_seed));
    }

    // Enforced no-logs (verifiable): all legitimate file setup (TUN, sockets, config read)
    // is done, so from here the process can be made *unable* to write to disk. Applied
    // across all tokio threads and inherited by any spawned later.
    if cfg.hardening.as_ref().is_some_and(|h| h.no_disk_writes) {
        oxide_seccomp::apply_no_disk_writes()
            .context("installing no-disk-writes seccomp filter")?;
        info!("enforced no-logs: seccomp filter installed (process cannot write to disk)");
    }

    // Run until Ctrl-C / SIGTERM, then tear down host state (leave-no-trace).
    tokio::select! {
        r = engine.run() => { r.context("engine stopped")?; }
        _ = shutdown_signal() => { info!("shutting down"); }
    }

    if nat_egress.is_some() {
        if let Err(e) = nat::disable_masquerade() {
            warn!(?e, "failed to remove nftables table");
        }
    }
    // TUN device is dropped here, removing the interface and its routes.
    Ok(())
}

/// Build the server-side [`Transport`] the config selects, binding/listening on
/// `listen_port`. Stealth transports require `obfuscation_key`; DAITA (`daita = true`)
/// requires a stealth transport. The QUIC transport enables decoy-forwarding when
/// `decoy_backend` is set.
async fn build_server_transport(iface: &InterfaceConfig, listen_port: u16) -> Result<Transport> {
    let kind = iface.transport_kind();
    if iface.daita && !kind.is_stealth() {
        anyhow::bail!("daita = true requires a stealth transport (obfs / quic / mimic)");
    }
    let key = || -> Result<[u8; 32]> {
        iface
            .obfuscation_key
            .as_ref()
            .map(|k| *k.as_bytes())
            .context("this transport requires interface.obfuscation_key")
    };
    // Bind dual-stack ([::]:port, IPV6_V6ONLY off) so the server serves both IPv4 and IPv6
    // clients on one socket (falls back to 0.0.0.0 if IPv6 is disabled).
    let bind_udp = || async {
        let std_sock = oxide_net_linux::bind_dual_stack(listen_port)
            .with_context(|| format!("binding UDP :{listen_port}"))?;
        tokio::net::UdpSocket::from_std(std_sock)
            .with_context(|| format!("binding UDP :{listen_port}"))
    };

    match kind {
        TransportKind::Plain => Ok(Transport::plain(bind_udp().await?)),
        TransportKind::Obfs => {
            info!("stealth: obfuscated transport");
            Ok(Transport::obfuscated(bind_udp().await?, key()?))
        }
        TransportKind::Quic => {
            let udp = bind_udp().await?;
            let k = key()?;
            match &iface.decoy_backend {
                Some(b) => {
                    let backend = tokio::net::lookup_host(b)
                        .await
                        .ok()
                        .and_then(|mut a| a.next())
                        .with_context(|| format!("resolving decoy_backend {b}"))?;
                    info!(%backend, "stealth: QUIC mimicry with decoy-forwarding");
                    Ok(Transport::quic_mimic_with_decoy(udp, k, backend))
                }
                None => {
                    info!("stealth: QUIC mimicry");
                    Ok(Transport::quic_mimic(udp, k))
                }
            }
        }
        TransportKind::Mimic => {
            info!("stealth: TLS mimicry (TCP)");
            let addr = std::net::SocketAddr::from(([0, 0, 0, 0], listen_port));
            let m = MimicTransport::bind(addr, key()?)
                .await
                .context("binding TLS-mimicry listener")?;
            Ok(Transport::mimic(m))
        }
    }
}

/// Periodically fetch this server's peer list from the control plane, reconcile it into
/// the running engine, and report live load back via a heartbeat. tokio's interval
/// fires immediately, so peers load at once.
async fn poll_control_plane<T: TunQueue>(
    handle: EngineHandle<T>,
    cp: ControlPlaneConfig,
    pq_seed: Option<Vec<u8>>,
) {
    let client = ControlClient::new(&cp.url);
    let mut tick = tokio::time::interval(Duration::from_secs(cp.poll_interval_secs.max(1)));
    // Relay listen ports we've already started (this server acting as a multihop entry).
    let mut running_relays: HashSet<u16> = HashSet::new();
    loop {
        tick.tick().await;
        match client.fetch_peers(&cp.server_id, &cp.token).await {
            Ok(entries) => {
                let desired: Vec<PeerParams> = entries
                    .iter()
                    .filter_map(|e| peer_from_entry(e, pq_seed.as_deref()))
                    .collect();
                info!(peers = desired.len(), "reconciled peers from control plane");
                handle.reconcile(desired);
            }
            Err(e) => warn!(error = %e, "failed to fetch peers from control plane"),
        }

        // Start any new relay routes for which this server is the entry.
        match client.fetch_relays(&cp.server_id, &cp.token).await {
            Ok(relays) => {
                for r in relays {
                    if running_relays.insert(r.listen_port) {
                        spawn_relay(r.listen_port, r.exit_endpoint).await;
                    }
                }
            }
            Err(e) => warn!(error = %e, "failed to fetch relay routes"),
        }

        // Report live load so the control plane can balance new clients across servers.
        let stats = handle.stats();
        if let Err(e) = client
            .heartbeat(&cp.server_id, &cp.token, stats.active_peers as u32)
            .await
        {
            warn!(error = %e, "heartbeat failed");
        }
    }
}

/// Bind and spawn a relay forwarding `listen_port` to `exit_endpoint` (host:port).
async fn spawn_relay(listen_port: u16, exit_endpoint: String) {
    let exit = match tokio::net::lookup_host(&exit_endpoint)
        .await
        .ok()
        .and_then(|mut a| a.next())
    {
        Some(addr) => addr,
        None => {
            warn!(exit = %exit_endpoint, "relay: cannot resolve exit endpoint");
            return;
        }
    };
    match Relay::bind(("0.0.0.0", listen_port), exit).await {
        Ok(relay) => {
            info!(listen_port, exit = %exit, "relay started (multihop entry)");
            tokio::spawn(async move {
                if let Err(e) = relay.run().await {
                    warn!(listen_port, error = %e, "relay stopped");
                }
            });
        }
        Err(e) => warn!(listen_port, error = %e, "relay: failed to bind"),
    }
}

/// Map a control-plane peer entry to engine params (server peers have no endpoint —
/// it's learned from the handshake). If the peer registered with post-quantum and we
/// have the PQ private seed, decapsulate its ciphertext into the peer's PSK.
fn peer_from_entry(entry: &PeerEntry, pq_seed: Option<&[u8]>) -> Option<PeerParams> {
    let allowed_ips: Vec<IpNet> = entry
        .allowed_ips
        .iter()
        .filter_map(|s| s.parse().ok())
        .collect();
    if allowed_ips.is_empty() {
        warn!(peer = %entry.public_key.to_base64(), "peer has no valid allowed_ips; skipping");
        return None;
    }
    let preshared_key = entry
        .pq_ciphertext
        .as_ref()
        .zip(pq_seed)
        .and_then(|(ct_b64, seed)| oxide_pq::decapsulate(seed, &B64.decode(ct_b64).ok()?));
    Some(PeerParams {
        public_key: entry.public_key,
        preshared_key,
        endpoint: None,
        allowed_ips,
        persistent_keepalive: None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_config_has_required_sections() {
        // private_key/obfuscation_key must parse as real 32-byte base64 SecretKeys.
        const KEY: &str = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
        let cfg = render_server_config(&ServerConfigParams {
            private_key_b64: KEY,
            address: "10.8.0.1/24",
            listen_port: 51820,
            dns: Some("10.8.0.1"),
            obfuscation_key: Some(KEY),
            pq_private_seed: Some("SEED"),
            transport: Some("quic"),
            daita: true,
            nat_egress: Some("eth0"),
            cp_url: "http://cp:8080",
            server_id: "us-1",
            token: "TOK",
        });
        // Parses as a valid server Config (has [control_plane], so validation passes).
        let parsed = oxide_common::Config::from_toml_str(&cfg).expect("valid config");
        assert_eq!(parsed.interface.listen_port, Some(51820));
        assert!(parsed.interface.daita);
        assert_eq!(
            parsed.interface.transport_kind(),
            oxide_common::TransportKind::Quic
        );
        assert!(parsed.interface.obfuscation_key.is_some());
        assert_eq!(parsed.interface.pq_private_seed.as_deref(), Some("SEED"));
        assert_eq!(parsed.nat.unwrap().egress.as_deref(), Some("eth0"));
        let cp = parsed.control_plane.unwrap();
        assert_eq!(cp.server_id, "us-1");
        assert_eq!(cp.token, "TOK");
    }

    #[test]
    fn nat_auto_omits_egress() {
        let cfg = render_server_config(&ServerConfigParams {
            private_key_b64: "P",
            address: "10.8.0.1/24",
            listen_port: 51820,
            dns: None,
            obfuscation_key: None,
            pq_private_seed: None,
            transport: None,
            daita: false,
            nat_egress: Some("auto"),
            cp_url: "http://cp:8080",
            server_id: "s",
            token: "t",
        });
        assert!(cfg.contains("[nat]"));
        assert!(!cfg.contains("egress =")); // auto → daemon detects
    }
}
