[package]
name = "oxide-client-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "oxide_client_core"
path = "src/lib.rs"

[dependencies]
oxide-common = { path = "../common" }
oxide-wg-core = { path = "../wg-core" }
oxide-net = { path = "../net" }
oxide-control-client = { path = "../control-client" }
oxide-pq = { path = "../pq" }
tokio = { workspace = true }
anyhow = { workspace = true }
ipnet = { workspace = true }
tracing = { workspace = true }
base64 = "0.22"

[dev-dependencies]
oxide-common = { path = "../common" }
